# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
# This is the Github action code used for CI runs
# The input system will in the future allow more then learn
# to be targeted by the profiles in this directory.
name: 'Check markdown codeblocks'
author: 'Zack Smith'
description: 'Run inspec against markdown'
inputs:
  profile:
    description: 'The profile to run'
    required: false
    default: 'all'
  markdown:
    description: 'The directory containing the markdown'
    required: true
  github_token:
    description: 'Github token used by github profile'
    required: true
  file_pattern:
    description: 'The file glob e.g. pages/**/*.mdx'
    required: true
  default_branch:
    description: 'The default branch in the target repository'
    default: 'master'
    required: false
outputs:
  inspec-output:
    description: 'The output of inspec'
runs:
  using: 'docker'
  image: 'docker://docker.mirror.hashicorp.services/hashieducation/inspec:master'
  env:
    MARKDOWN: ${{ inputs.markdown }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    FILE_PATTERN: ${{ inputs.file_pattern }}
    DEFAULT_BRANCH: ${{ inputs.default_branch }}
  args:
    - 'exec'
    - /profiles/${{ inputs.profile }}
    - '--target=docker://inspec-target'
    - '--reporter'
    - 'cli'
    - 'html:inspec.html'
    - '--show-progress'
    - '--no-color'
    - '--no-distinct-exit'
    - '--input-file'
    - '/input.yml'
branding:
  color: 'black'
  icon: 'dollar-sign'
